# SPRSUN Heat Pump - BoneIO Integration Example
# This example shows how to integrate SPRSUN heat pump package with BoneIO 32x10 board
# Based on the current usage pattern in boneio-32-sw-01.yaml

substitutions:
  name: "boneio-32-sw-01"
  friendly_name: BoneIO ESP 32x10
  serial_prefix: esp   #Don't change it.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: boneio.32x10-lights
    version: '0.7'
  on_boot:
    - priority: -100.0
      then:
        if:
          condition:
            binary_sensor.is_on: sprsun_defrost
          then:
            - globals.set:
                id: number_compressor_starts
                value: '0'

esp32:
  board: nodemcu-32s

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-32x10_switches_v0_7.yaml@latest
  import_full_config: true

packages:
  # BoneIO internal packages
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files: [devices/buzzer.yaml, devices_v0_7/display.yaml, devices/serial_no.yaml,
      devices_v0_7/i2c.yaml, devices_v0_7-v0_9/ina219.yaml, devices_v0_7-v0_9/lm75b.yaml,
      devices_v0_7-v0_9/pcf.yaml, boards/output/out01_02.yaml, boards/output/out03_04.yaml,
      boards/output/out05_06.yaml, boards/output/out07_08.yaml, boards/output/out09_10.yaml,
      boards/output/out11_12.yaml, boards/output/out13_14.yaml, boards/output/out15_16.yaml,
      boards/output/out17_18.yaml, boards/output/out19_20.yaml, boards/output/out21_22.yaml,
      boards/output/out23_24.yaml, boards/output/out25_26.yaml, boards/output/out27_28.yaml,
      boards/output/out29_30.yaml, boards/output/out31_32.yaml]
  
  # SPRSUN Heat Pump Integration Package - Git Integration
  sprsun_package:
    url: https://github.com/plebann/sprsun-esphome-package
    files: [packages/sprsun/complete.yaml]
    ref: main
    refresh: 1d
    vars:
      sprsun_device_prefix: "sprsun"
      sprsun_device_name: "SPRSUN"
      sprsun_uart_rx_pin: "GPIO14"
      sprsun_uart_tx_pin: "GPIO15"
      sprsun_uart_baud: "19200"
      sprsun_uart_stop_bits: "2"
      sprsun_modbus_address: "1"
      sprsun_modbus_send_wait: "200ms"
      sprsun_update_interval: "5s"
      sprsun_setup_priority: "-10"

logger:
  level: INFO

api:
  reboot_timeout: 0s

ota:
- platform: esphome
- platform: web_server

web_server:
  port: 80
  local: true

time:
- platform: homeassistant
  timezone: Europe/Warsaw
  id: homeassistant_time

switch:
  - platform: output
    name: Switch 01
    output: out_01
    id: switch_01
  - platform: output
    name: Switch 02
    output: out_02
    id: switch_02
  - platform: output
    name: Switch 03
    output: out_03
    id: switch_03
  - platform: output
    name: Switch 32
    output: out_32
    id: switch_32