# Test Configuration - GitHub Shorthand Method
# This validates the simplest Git integration approach

substitutions:
  device_name: "test-shorthand"
  friendly_name: "Test Shorthand"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: nodemcu-32s

logger:
  level: INFO
  baud_rate: 0

packages:
  # GitHub shorthand method - simplest approach
  sprsun: github://plebann/sprsun-esphome-package/packages/sprsun/complete.yaml@main

# NOTE: GitHub shorthand method has limitations with variables
# This would require default values in the package or would fail
# This test demonstrates the limitation of the shorthand approach