# Test Configuration - Variable Customization
# This validates different variable combinations and edge cases

substitutions:
  device_name: "test-variables"
  friendly_name: "Test Variables"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev

logger:
  level: DEBUG
  baud_rate: 0

packages:
  # Test with custom variable values
  sprsun_custom:
    url: https://github.com/plebann/sprsun-esphome-package
    files: [packages/sprsun/complete.yaml]
    ref: main
    refresh: 6h  # Different refresh interval
    vars:
      # Custom naming
      sprsun_device_prefix: "custom_pump"
      sprsun_device_name: "Custom SPRSUN Unit"
      
      # Different UART pins
      sprsun_uart_rx_pin: "GPIO32"
      sprsun_uart_tx_pin: "GPIO33"
      
      # Different communication settings
      sprsun_uart_baud: "9600"  # Slower baud rate
      sprsun_uart_stop_bits: "1"
      sprsun_modbus_address: "2"  # Different Modbus address
      sprsun_modbus_send_wait: "300ms"  # Slower communication
      
      # Different update intervals
      sprsun_update_interval: "15s"  # Slower updates
      sprsun_setup_priority: "-5"  # Different priority

# This configuration tests:
# - Non-standard variable values
# - Different UART configuration
# - Custom device naming
# - Modified timing parameters