# Test Configuration - Full Git Configuration Method
# This validates the recommended approach with full variable support

substitutions:
  device_name: "test-full-git"
  friendly_name: "Test Full Git"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: nodemcu-32s

logger:
  level: INFO
  baud_rate: 0  # Disable UART logging since we use it for Modbus

packages:
  # Full Git configuration with all variables
  sprsun_package:
    url: https://github.com/plebann/sprsun-esphome-package
    files: [packages/sprsun/complete.yaml]
    ref: main
    refresh: 1d
    vars:
      sprsun_device_prefix: "test_hp"
      sprsun_device_name: "Test Heat Pump"
      sprsun_uart_rx_pin: "GPIO16"
      sprsun_uart_tx_pin: "GPIO17"
      sprsun_uart_baud: "19200"
      sprsun_uart_stop_bits: "2"
      sprsun_modbus_address: "1"
      sprsun_modbus_send_wait: "200ms"
      sprsun_update_interval: "5s"
      sprsun_setup_priority: "-10"