# SPRSUN Heat Pump Package - Binary Sensors
# Part of the modular SPRSUN heat pump integration package

binary_sensor:
  # Heating status binary sensor
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Heating
    id: ${sprsun_device_prefix}_heating
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0003
    bitmask: 0x02

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Cooling
    id: ${sprsun_device_prefix}_cooling
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0003
    bitmask: 0x20

  # Defrost status binary sensor with counter automation
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Defrost
    id: ${sprsun_device_prefix}_defrost
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0003
    bitmask: 0x80
    on_press:
      then:
        - lambda: 'id(number_defrost)++;'

  # Compressor status binary sensor with counter automation
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Compressor
    id: ${sprsun_device_prefix}_compressor
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0004
    bitmask: 0x01
    on_press:
      then:
        - lambda: 'id(number_compressor_starts)++;'

  # Heating heater status binary sensor
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Heating heater
    id: ${sprsun_device_prefix}_heating_heater
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0005
    bitmask: 0x0020

  # Chassis heater status binary sensor
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Chassis heater
    id: ${sprsun_device_prefix}_chassis_heater
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0005
    bitmask: 0x0001

  # Frequency conversion failure detection
  - platform: template
    name: ${sprsun_device_name} Frequency conversion failure
    id: ${sprsun_device_prefix}_freq_conversion_failure
    device_class: problem
    entity_category: diagnostic
    lambda: |-
      // Check if any frequency conversion failure registers have non-zero values
      return (id(${sprsun_device_prefix}_freq_failure_1).state > 0 ||
              id(${sprsun_device_prefix}_freq_failure_2).state > 0 ||
              id(${sprsun_device_prefix}_freq_failure_3).state > 0 ||
              id(${sprsun_device_prefix}_freq_failure_4).state > 0);

  # Missing valve and pump status sensors
  # 4-way valve status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} 4-way valve
    id: ${sprsun_device_prefix}_4way_valve
    entity_category: diagnostic
    register_type: holding
    address: 0x0004
    bitmask: 0x40

  # Three-way valve status  
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Three-way valve
    id: ${sprsun_device_prefix}_3way_valve
    entity_category: diagnostic
    register_type: holding
    address: 0x0005
    bitmask: 0x40

  # Hot water heater status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Hot water heater
    id: ${sprsun_device_prefix}_hotwater_heater
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0005
    bitmask: 0x80

  # A/C Pump status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} A/C Pump
    id: ${sprsun_device_prefix}_ac_pump
    entity_category: diagnostic
    register_type: holding
    address: 0x0006
    bitmask: 0x01

  # Crank heater status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Crank heater
    id: ${sprsun_device_prefix}_crank_heater
    entity_category: diagnostic
    device_class: heat
    register_type: holding
    address: 0x0006
    bitmask: 0x02

  # Assistant solenoid valve status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Assistant solenoid valve
    id: ${sprsun_device_prefix}_assistant_solenoid
    entity_category: diagnostic
    register_type: holding
    address: 0x0006
    bitmask: 0x20

  # Pump status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Pump
    id: ${sprsun_device_prefix}_pump
    entity_category: diagnostic
    register_type: holding
    address: 0x0006
    bitmask: 0x40

  # With/without heating status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} With heating
    id: ${sprsun_device_prefix}_with_heating
    entity_category: diagnostic
    register_type: holding
    address: 0x0003
    bitmask: 0x04

  # With/without cooling status
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} With cooling
    id: ${sprsun_device_prefix}_with_cooling
    entity_category: diagnostic
    register_type: holding
    address: 0x0003
    bitmask: 0x08