# SPRSUN Heat Pump Package - Sensors
# Part of the modular SPRSUN heat pump integration package

sensor:
  # Basic temperature and status sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Hot water temp
    id: ${sprsun_device_prefix}_hot_water_temp
    register_type: holding
    address: 0x0020
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
      - round: 1

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Outlet water temp
    id: ${sprsun_device_prefix}_outlet_water_temp
    register_type: holding
    address: 0x0021
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Inlet water temp
    id: ${sprsun_device_prefix}_inlet_water_temp
    register_type: holding
    address: 0x0022
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Ambient temp
    id: ${sprsun_device_prefix}_ambient_temp
    register_type: holding
    address: 0x0023
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Coil temp
    id: ${sprsun_device_prefix}_coil_temp
    register_type: holding
    address: 0x0024
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Pressure sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Low pressure
    id: ${sprsun_device_prefix}_low_pressure
    register_type: holding
    address: 0x0025
    value_type: S_WORD
    unit_of_measurement: "bar"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} High pressure
    id: ${sprsun_device_prefix}_high_pressure
    register_type: holding
    address: 0x0026
    value_type: S_WORD
    unit_of_measurement: "bar"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Exhaust temperature sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Exhaust temp
    id: ${sprsun_device_prefix}_exhaust_temp
    register_type: holding
    address: 0x0027
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Machine running status sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Machine running status 1
    id: ${sprsun_device_prefix}_machine_status_1
    register_type: holding
    address: 0x0028
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Machine running status 2
    id: ${sprsun_device_prefix}_machine_status_2
    register_type: holding
    address: 0x0029
    value_type: U_WORD

  # Additional gas temperature sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Gas inlet temp
    id: ${sprsun_device_prefix}_gas_inlet_temp
    register_type: holding
    address: 0x002A
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Gas outlet temp
    id: ${sprsun_device_prefix}_gas_outlet_temp
    register_type: holding
    address: 0x002B
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Additional status sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Machine running status 3
    id: ${sprsun_device_prefix}_machine_status_3
    register_type: holding
    address: 0x002C
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Machine running status 4
    id: ${sprsun_device_prefix}_machine_status_4
    register_type: holding
    address: 0x002D
    value_type: U_WORD

  # Compressor frequency and current
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Comp Frequency
    id: ${sprsun_device_prefix}_comp_frequency
    register_type: holding
    address: 0x002E
    value_type: U_WORD
    unit_of_measurement: "Hz"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Comp current
    id: ${sprsun_device_prefix}_comp_current
    register_type: holding
    address: 0x002F
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Fan RPM sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Fan 1 RPM
    id: ${sprsun_device_prefix}_fan_1_rpm
    register_type: holding
    address: 0x0030
    value_type: U_WORD
    unit_of_measurement: "rpm"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Fan 2 RPM
    id: ${sprsun_device_prefix}_fan_2_rpm
    register_type: holding
    address: 0x0031
    value_type: U_WORD
    unit_of_measurement: "rpm"
    accuracy_decimals: 0

  # EEV (Electronic Expansion Valve) position
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} EEV position
    id: ${sprsun_device_prefix}_eev_position
    register_type: holding
    address: 0x0032
    value_type: U_WORD
    unit_of_measurement: "steps"
    accuracy_decimals: 0

  # Current step value
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Current step value
    id: ${sprsun_device_prefix}_current_step_value
    register_type: holding
    address: 0x0033
    value_type: U_WORD

  # Runtime counters
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Comp total runtime
    id: ${sprsun_device_prefix}_comp_total_runtime
    register_type: holding
    address: 0x0035
    value_type: U_DWORD
    unit_of_measurement: "h"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Unit total runtime
    id: ${sprsun_device_prefix}_unit_total_runtime
    register_type: holding
    address: 0x0037
    value_type: U_DWORD
    unit_of_measurement: "h"
    accuracy_decimals: 0

  # Power consumption
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Power
    id: ${sprsun_device_prefix}_power
    register_type: holding
    address: 0x0039
    value_type: U_WORD
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - multiply: 100

  # Current consumption by phases
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} L1 current
    id: ${sprsun_device_prefix}_l1_current
    register_type: holding
    address: 0x003A
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} L2 current
    id: ${sprsun_device_prefix}_l2_current
    register_type: holding
    address: 0x003B
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} L3 current
    id: ${sprsun_device_prefix}_l3_current
    register_type: holding
    address: 0x003C
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Voltage by phases
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} L1 voltage
    id: ${sprsun_device_prefix}_l1_voltage
    register_type: holding
    address: 0x003D
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} L2 voltage
    id: ${sprsun_device_prefix}_l2_voltage
    register_type: holding
    address: 0x003E
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} L3 voltage
    id: ${sprsun_device_prefix}_l3_voltage
    register_type: holding
    address: 0x003F
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 0