# SPRSUN Heat Pump Package - Sensors
# Part of the modular SPRSUN heat pump integration package

sensor:
  # Controller and Display version sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Controller version
    id: ${sprsun_device_prefix}_controller_version
    register_type: holding
    address: 0x002C
    value_type: U_WORD
    entity_category: diagnostic
    icon: mdi:chip
    skip_updates: 10
 
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Display version
    id: ${sprsun_device_prefix}_display_version
    register_type: holding
    address: 0x002D
    value_type: U_WORD
    entity_category: diagnostic
    icon: mdi:monitor
    skip_updates: 10

  # Compressor start counter
  - platform: template
    name: ${sprsun_device_name} Compressor starts
    id: ${sprsun_device_prefix}_number_of_compressor_starts
    icon: mdi:counter
    unit_of_measurement: "starts"
    accuracy_decimals: 0
    lambda: 'return id(number_compressor_starts);'
    state_class: measurement

  # Defrost counter
  - platform: template
    name: ${sprsun_device_name} Defrosts count
    id: ${sprsun_device_prefix}_defrosts_count
    icon: mdi:counter
    unit_of_measurement: "defrosts"
    accuracy_decimals: 0
    lambda: 'return id(number_defrost);'
    state_class: measurement

  # Duty time sensors
  - platform: duty_time
    name: ${sprsun_device_name} Work Heating time
    id: ${sprsun_device_prefix}_heating_work_time
    sensor: ${sprsun_device_prefix}_heating
    restore: true
    last_time:
      name: Last time ${sprsun_device_name} Heating time

  - platform: duty_time
    name: ${sprsun_device_name} Work Cooling time
    id: ${sprsun_device_prefix}_cooling_work_time
    sensor: ${sprsun_device_prefix}_cooling
    restore: true
    last_time:
      name: Last time ${sprsun_device_name} Cooling time

  - platform: duty_time
    name: ${sprsun_device_name} Compressor time
    id: ${sprsun_device_prefix}_compressor_work_time
    sensor: ${sprsun_device_prefix}_compressor
    restore: true
    last_time:
      name: Last time ${sprsun_device_name} Compressor time

  # Temperature sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Inlet temperature
    id: ${sprsun_device_prefix}_inlet_temp
    register_type: holding
    address: 0x000E 
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.1;'
    accuracy_decimals: 2
 
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Outlet temperature
    id: ${sprsun_device_prefix}_outlet_temp
    register_type: holding
    address: 0x0012
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.1;'
    accuracy_decimals: 2

  # Delta temperature calculation
  - platform: template
    name: ${sprsun_device_name} Delta
    id: ${sprsun_device_prefix}_delta
    icon: mdi:delta
    unit_of_measurement: "°C"
    device_class: "temperature"
    accuracy_decimals: 2
    update_interval: ${sprsun_update_interval}
    lambda: 'return id(${sprsun_device_prefix}_outlet_temp).state - id(${sprsun_device_prefix}_inlet_temp).state;'

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Ambient temperature
    id: ${sprsun_device_prefix}_ambi_temp
    register_type: holding
    address: 0x0011
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.5;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Power
    id: ${sprsun_device_prefix}_power_w
    register_type: holding
    address: 0x0017
    unit_of_measurement: "W"
    device_class: "power"
    value_type: U_WORD
    filters:
      - lambda: 'return x * 1.0;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Compressor frequency
    id: ${sprsun_device_prefix}_comp_frequency
    register_type: holding
    address: 0x001E
    unit_of_measurement: "Hz"
    device_class: "frequency"
    value_type: U_WORD
    filters:
      - lambda: 'return x * 1.0;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Compressor target frequency
    id: ${sprsun_device_prefix}_comp_frequency_target
    register_type: holding
    address: 0x0024
    unit_of_measurement: "Hz"
    device_class: "frequency"
    value_type: U_WORD
    filters:
      - lambda: 'return x * 1.0;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Fan speed
    id: ${sprsun_device_prefix}_fan_speed
    register_type: holding
    address: 0x0026
    unit_of_measurement: "RPM"
    value_type: U_WORD
    filters:
      - lambda: 'return x * 1.0;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Fan target speed
    id: ${sprsun_device_prefix}_fan_target
    register_type: holding
    address: 0x0031
    unit_of_measurement: "RPM"
    value_type: U_WORD
    filters:
      - lambda: 'return x * 1.0;'
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Pump speed
    id: ${sprsun_device_prefix}_pump_speed
    register_type: holding
    address: 0x002E
    unit_of_measurement: "%"
    value_type: U_WORD
    filters:
      - lambda: 'return x * 1.0;'
    accuracy_decimals: 1

  # Parameter marker (used for bit manipulation in controls)
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    id: parameter_marker_definition_raw
    register_type: holding
    address: 0x0032
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Heating Temperature
    id: ${sprsun_device_prefix}_heating_temp
    register_type: holding
    address: 0x00CC
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.5;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Cooling Temperature
    id: ${sprsun_device_prefix}_cooling_temp
    register_type: holding
    address: 0x00CB
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.5;'
    accuracy_decimals: 2

  # Pressure sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Suction pressure
    id: ${sprsun_device_prefix}_suct_press
    register_type: holding
    address: 0x002F
    unit_of_measurement: "bar"
    device_class: "pressure"
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1
 
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Discharge pressure
    id: ${sprsun_device_prefix}_disch_press
    register_type: holding
    address: 0x0030
    unit_of_measurement: "bar"
    device_class: "pressure"
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1

  # Additional temperature sensors
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Suction gas temperature
    id: ${sprsun_device_prefix}_suct_gas_temp
    register_type: holding
    address: 0x0015
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.5;'
    accuracy_decimals: 2
 
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Coil temperature
    id: ${sprsun_device_prefix}_coil_temp
    register_type: holding
    address: 0x0016
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.5;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Exhaust temperature
    id: ${sprsun_device_prefix}_exhaust_temp
    register_type: holding
    address: 0x001B
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 1.0;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Evaporator temperature
    id: ${sprsun_device_prefix}_evap_temp
    register_type: holding
    address: 0x0028
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.1;'
    accuracy_decimals: 2
 
  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Condenser temperature
    id: ${sprsun_device_prefix}_cond_temp
    register_type: holding
    address: 0x0029
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.1;'
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: ${sprsun_device_prefix}_pc
    name: ${sprsun_device_name} Driving temperature
    id: ${sprsun_device_prefix}_driving_temp
    register_type: holding
    address: 0x0022
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: 'return x * 0.5;'
    accuracy_decimals: 1